channels:
  - openbabel
  - conda-forge
  - defaults
dependencies:
  - biopandas
  - cython
  - numpy
  - numpy-base
  - openbabel
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pip
  - py3dmol
  - python
  - python-dateutil
  - python-leveldb
  - python_abi
  - rdkit
  - scipy
  - six
  - pip
